ci(GithubAction): manul target set

diff --git a/.github/workflows/Build-status-checks.yml b/.github/workflows/Build-status-checks.yml
--- a/.github/workflows/Build-status-checks.yml
+++ b/.github/workflows/Build-status-checks.yml
@@ -54,7 +54,6 @@ jobs:
             const seconds = d.getSeconds();
             console.log(\`\${year} \${month} \${day}, \${hours}:\${minutes}:\${seconds}\`);
           ") >> $GITHUB_ENV
-          # echo "Target_BUILD=$(echo '["test","foo","bar"]' | base64 | tr -d '\n' )" >> $GITHUB_ENV
 
       - name: File Change Target Mapping
         uses: actions/github-script@v7
@@ -137,7 +136,7 @@ jobs:
               const Files_Modified = `<li><b>Files Modified:</b><ol>${totalChangedFilesList}</ol></li>`;
               const Commit_Messages = `<li><b>Commit Messages:</b><ol>${commitMessagesList}</ol></li>`;
               const Started_At = `<li><b>Started At:</b> <code>${started_at}</code></li>`;
-              const Finished_At = `<li><b>Finished_At At:</b> <code>${finished_At}</code></li>`;
+              const Finished_At = `<li><b>Finished At:</b> <code>${finished_At}</code></li>`;
               const Status_footer = `</br><b>Build Target:</b> ${components_build_target}`;
 
               const Message_body = [
@@ -190,8 +189,62 @@ jobs:
       - name: Perform Selective Compilation Task
         id: perform_skip_task
         run: |
-          echo "Performing task..."
-          echo ${{env.Target_BUILD}}
+          echo "Performing Selective Compilation task..."
+          TARGET=$(echo ${{env.Target_BUILD}} | base64 -d)
+
+          TARGET_REVERSEPROXY=$(echo $TARGET | jq 'contains(["reverseProxy"])')
+          TARGET_WAF=$(echo $TARGET | jq 'contains(["waf"])')
+          TARGET_APPLICATION=$(echo $TARGET | jq 'contains(["application"])')
+          TARGET_SERVER=$(echo $TARGET | jq 'contains(["server"])')
+          TARGET_SIMULATOR=$(echo $TARGET | jq 'contains(["simulator"])')
+          TARGET_DOCUMENTATION=$(echo $TARGET | jq 'contains(["documentation"])')
+          TARGET_ALL=$(echo $TARGET | jq 'contains(["all"])')
+
+          echo "REVERSEPROXY   Need build? => $TARGET_REVERSEPROXY"
+          echo "WAF            Need build? => $TARGET_WAF"
+          echo "APPLICATION    Need build? => $TARGET_APPLICATION"
+          echo "SERVER         Need build? => $TARGET_SERVER"
+          echo "SIMULATOR      Need build? => $TARGET_SIMULATOR"
+          echo "DOCUMENTATION  Need build? => $TARGET_DOCUMENTATION"
+          echo "ALL            Need build? => $TARGET_ALL"
+
+          echo -e "\n\n"
+          build_reverseProxy(){
+           echo "building reverseProxy..."
+          }
+
+          build_waf(){
+           echo "building waf..."
+          }
+
+          build_application(){
+           echo "building application..."
+          }
+
+          build_server(){
+           echo "building server..."
+          }
+
+          build_simulator(){
+           echo "building simulator..."
+          }
+
+          build_documentation(){
+           echo "building documentation..."
+          }
+
+          build_all(){
+           echo "building all..."
+          }
+
+          [[ $TARGET_REVERSEPROXY == "true" ]] && build_reverseProxy || echo "TARGET_REVERSEPROXY not found skipping..."
+          [[ $TARGET_WAF == "true" ]] && build_waf || echo "TARGET_WAF not found skipping..."
+          [[ $TARGET_APPLICATION == "true" ]] && build_application || echo "TARGET_APPLICATION not found skipping..."
+          [[ $TARGET_SERVER == "true" ]] && build_server || echo "TARGET_SERVER not found skipping..."
+          [[ $TARGET_SIMULATOR == "true" ]] && build_simulator || echo "TARGET_SIMULATOR not found skipping..."
+          [[ $TARGET_DOCUMENTATION == "true" ]] && build_documentation || echo "TARGET_DOCUMENTATION not found skipping..."
+          [[ $TARGET_ALL == "true" ]] && build_all || echo "TARGET_ALL not found skipping..."
+
           sleep 30
           echo "updating status..."
       
